# TCL File Generated by Component Editor 9.0sp1
# Thu Jun 18 15:18:00 GMT+08:00 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | pipelined_read_burst_write_fir_dma "pipelined_read_burst_write_fir_dma" v1.0
# | JCJB 2009.06.18.15:18:00
# | DMA with read latency awareness and write bursting capabilities
# | 
# | C:/Projects/SPR/308211_jarrod/porting_3c120_to_90/nios_lcd_3c120/dma/pipelined_read_burst_write_dma.v
# | 
# |    ./pipelined_read_burst_write_dma.v syn
# |    ./latency_aware_read_master.v syn
# |    ./transform_block.v syn
# |    ./burst_write_master.v syn
# |    ./slave.v syn
# |    ./custom_FIR.v syn
# |    ./coefs.h syn
# | 
# +-----------------------------------


# +-----------------------------------
# | module pipelined_read_burst_write_fir_dma
# | 
set_module_property DESCRIPTION "DMA with read latency awareness and write bursting capabilities"
set_module_property NAME pipelined_read_burst_write_fir_dma
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP Custom_DMA
set_module_property AUTHOR JCJB
set_module_property ICON_PATH ALTERA_LOGO_ANIM.gif
set_module_property DISPLAY_NAME pipelined_read_burst_write_fir_dma
set_module_property TOP_LEVEL_HDL_FILE pipelined_read_burst_write_dma.v
set_module_property TOP_LEVEL_HDL_MODULE pipelined_read_burst_write_dma
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file pipelined_read_burst_write_dma.v SYNTHESIS
add_file latency_aware_read_master.v SYNTHESIS
add_file transform_block.v SYNTHESIS
add_file burst_write_master.v SYNTHESIS
add_file slave.v SYNTHESIS
add_file custom_FIR.v SYNTHESIS
add_file coefs.h SYNTHESIS
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter DATAWIDTH INTEGER 32
set_parameter_property DATAWIDTH DISPLAY_NAME DATAWIDTH
set_parameter_property DATAWIDTH UNITS None
set_parameter_property DATAWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATAWIDTH DISPLAY_HINT ""
set_parameter_property DATAWIDTH AFFECTS_GENERATION false
set_parameter_property DATAWIDTH IS_HDL_PARAMETER true
add_parameter BYTEENABLEWIDTH INTEGER 4
set_parameter_property BYTEENABLEWIDTH DISPLAY_NAME BYTEENABLEWIDTH
set_parameter_property BYTEENABLEWIDTH UNITS None
set_parameter_property BYTEENABLEWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BYTEENABLEWIDTH DISPLAY_HINT ""
set_parameter_property BYTEENABLEWIDTH AFFECTS_GENERATION false
set_parameter_property BYTEENABLEWIDTH IS_HDL_PARAMETER true
add_parameter ADDRESSWIDTH INTEGER 32
set_parameter_property ADDRESSWIDTH DISPLAY_NAME ADDRESSWIDTH
set_parameter_property ADDRESSWIDTH UNITS None
set_parameter_property ADDRESSWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDRESSWIDTH DISPLAY_HINT ""
set_parameter_property ADDRESSWIDTH AFFECTS_GENERATION false
set_parameter_property ADDRESSWIDTH IS_HDL_PARAMETER true
add_parameter FIFOUSEMEMORY INTEGER 1
set_parameter_property FIFOUSEMEMORY DISPLAY_NAME FIFOUSEMEMORY
set_parameter_property FIFOUSEMEMORY UNITS None
set_parameter_property FIFOUSEMEMORY ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFOUSEMEMORY DISPLAY_HINT ""
set_parameter_property FIFOUSEMEMORY AFFECTS_GENERATION false
set_parameter_property FIFOUSEMEMORY IS_HDL_PARAMETER true
add_parameter READ_FIFODEPTH INTEGER 32
set_parameter_property READ_FIFODEPTH DISPLAY_NAME READ_FIFODEPTH
set_parameter_property READ_FIFODEPTH UNITS None
set_parameter_property READ_FIFODEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property READ_FIFODEPTH DISPLAY_HINT ""
set_parameter_property READ_FIFODEPTH AFFECTS_GENERATION false
set_parameter_property READ_FIFODEPTH IS_HDL_PARAMETER true
add_parameter READ_FIFODEPTH_LOG2 INTEGER 5
set_parameter_property READ_FIFODEPTH_LOG2 DISPLAY_NAME READ_FIFODEPTH_LOG2
set_parameter_property READ_FIFODEPTH_LOG2 UNITS None
set_parameter_property READ_FIFODEPTH_LOG2 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property READ_FIFODEPTH_LOG2 DISPLAY_HINT ""
set_parameter_property READ_FIFODEPTH_LOG2 AFFECTS_GENERATION false
set_parameter_property READ_FIFODEPTH_LOG2 IS_HDL_PARAMETER true
add_parameter WRITE_FIFODEPTH INTEGER 32
set_parameter_property WRITE_FIFODEPTH DISPLAY_NAME WRITE_FIFODEPTH
set_parameter_property WRITE_FIFODEPTH UNITS None
set_parameter_property WRITE_FIFODEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WRITE_FIFODEPTH DISPLAY_HINT ""
set_parameter_property WRITE_FIFODEPTH AFFECTS_GENERATION false
set_parameter_property WRITE_FIFODEPTH IS_HDL_PARAMETER true
add_parameter WRITE_FIFODEPTH_LOG2 INTEGER 5
set_parameter_property WRITE_FIFODEPTH_LOG2 DISPLAY_NAME WRITE_FIFODEPTH_LOG2
set_parameter_property WRITE_FIFODEPTH_LOG2 UNITS None
set_parameter_property WRITE_FIFODEPTH_LOG2 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WRITE_FIFODEPTH_LOG2 DISPLAY_HINT ""
set_parameter_property WRITE_FIFODEPTH_LOG2 AFFECTS_GENERATION false
set_parameter_property WRITE_FIFODEPTH_LOG2 IS_HDL_PARAMETER true
add_parameter WRITE_MAXBURSTCOUNT INTEGER 4
set_parameter_property WRITE_MAXBURSTCOUNT DISPLAY_NAME WRITE_MAXBURSTCOUNT
set_parameter_property WRITE_MAXBURSTCOUNT UNITS None
set_parameter_property WRITE_MAXBURSTCOUNT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WRITE_MAXBURSTCOUNT DISPLAY_HINT ""
set_parameter_property WRITE_MAXBURSTCOUNT AFFECTS_GENERATION false
set_parameter_property WRITE_MAXBURSTCOUNT IS_HDL_PARAMETER true
add_parameter WRITE_MAXBURSTCOUNT_WIDTH INTEGER 3
set_parameter_property WRITE_MAXBURSTCOUNT_WIDTH DISPLAY_NAME WRITE_MAXBURSTCOUNT_WIDTH
set_parameter_property WRITE_MAXBURSTCOUNT_WIDTH UNITS None
set_parameter_property WRITE_MAXBURSTCOUNT_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WRITE_MAXBURSTCOUNT_WIDTH DISPLAY_HINT ""
set_parameter_property WRITE_MAXBURSTCOUNT_WIDTH AFFECTS_GENERATION false
set_parameter_property WRITE_MAXBURSTCOUNT_WIDTH IS_HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock ptfSchematicName ""

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
add_interface_port clock reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point control
# | 
add_interface control avalon end
set_interface_property control addressAlignment DYNAMIC
set_interface_property control bridgesToMaster ""
set_interface_property control burstOnBurstBoundariesOnly false
set_interface_property control holdTime 0
set_interface_property control isMemoryDevice false
set_interface_property control isNonVolatileStorage false
set_interface_property control linewrapBursts false
set_interface_property control maximumPendingReadTransactions 0
set_interface_property control printableDevice false
set_interface_property control readLatency 1
set_interface_property control readWaitStates 0
set_interface_property control readWaitTime 0
set_interface_property control setupTime 0
set_interface_property control timingUnits Cycles
set_interface_property control writeWaitTime 0

set_interface_property control ASSOCIATED_CLOCK clock
set_interface_property control ENABLED true

add_interface_port control slave_address address Input 3
add_interface_port control slave_writedata writedata Input 32
add_interface_port control slave_write write Input 1
add_interface_port control slave_read read Input 1
add_interface_port control slave_byteenable byteenable Input 4
add_interface_port control slave_readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point read_master
# | 
add_interface read_master avalon start
set_interface_property read_master adaptsTo ""
set_interface_property read_master burstOnBurstBoundariesOnly false
set_interface_property read_master doStreamReads false
set_interface_property read_master doStreamWrites false
set_interface_property read_master linewrapBursts false

set_interface_property read_master ASSOCIATED_CLOCK clock
set_interface_property read_master ENABLED true

add_interface_port read_master read_master_address address Output -1
add_interface_port read_master read_master_read read Output 1
add_interface_port read_master read_master_byteenable byteenable Output -1
add_interface_port read_master read_master_readdata readdata Input -1
add_interface_port read_master read_master_readdatavalid readdatavalid Input 1
add_interface_port read_master read_master_waitrequest waitrequest Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point write_master
# | 
add_interface write_master avalon start
set_interface_property write_master adaptsTo ""
set_interface_property write_master burstOnBurstBoundariesOnly false
set_interface_property write_master doStreamReads false
set_interface_property write_master doStreamWrites false
set_interface_property write_master linewrapBursts false

set_interface_property write_master ASSOCIATED_CLOCK clock
set_interface_property write_master ENABLED true

add_interface_port write_master write_master_address address Output -1
add_interface_port write_master write_master_write write Output 1
add_interface_port write_master write_master_byteenable byteenable Output -1
add_interface_port write_master write_master_writedata writedata Output -1
add_interface_port write_master write_master_waitrequest waitrequest Input 1
add_interface_port write_master write_master_burstcount burstcount Output -1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point irq
# | 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint control

set_interface_property irq ASSOCIATED_CLOCK clock
set_interface_property irq ENABLED true

add_interface_port irq slave_irq irq Output 1
# | 
# +-----------------------------------
