# TCL File Generated by Component Editor 8.0sp1
# Fri Sep 26 11:22:07 IST 2008
# DO NOT MODIFY


# +-----------------------------------
# | 
# | sls_sdhc_top "SD Host Controller -- SLS" v2.0
# | Hardik Sheth 2008.09.26.11:22:07
# | SD Host Controller -- SLS 
# | 
# | 
# | 
# |    ./sls_sdhc_top.v syn, sim
# |    ./sls_sdhc_clkgen.v syn, sim
# |    ./sls_sdhc_cmd.v syn, sim
# |    ./sls_sdhc_cntrl.v syn, sim
# |    ./sls_sdhc_crc16_1bit.v syn, sim
# |    ./sls_sdhc_crc16_4bit.v syn, sim
# |    ./sls_sdhc_crc7.v syn, sim
# |    ./sls_sdhc_data.v syn, sim
# |    ./sls_sdhc_dma_rd.v syn, sim
# |    ./sls_sdhc_dma_wr.v syn, sim
# |    ./sls_sdhc_rx_fifo.v syn, sim
# |    ./sls_sdhc_tx_fifo.v syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module sls_sdhc_top
# | 
set_module_property DESCRIPTION "SD Host Controller -- SLS"
set_module_property NAME sls_sdhc_top
set_module_property VERSION 2.0
set_module_property GROUP SLS
set_module_property AUTHOR "Hardik Sheth"
set_module_property ICON_PATH SLS_logo.jpg
set_module_property DISPLAY_NAME "SD Host Controller -- SLS"
set_module_property TOP_LEVEL_HDL_FILE sls_sdhc_top.v
set_module_property TOP_LEVEL_HDL_MODULE sls_sdhc_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file sls_sdhc_top.v {SYNTHESIS SIMULATION}
add_file sls_sdhc_clkgen.v {SYNTHESIS SIMULATION}
add_file sls_sdhc_cmd.v {SYNTHESIS SIMULATION}
add_file sls_sdhc_cntrl.v {SYNTHESIS SIMULATION}
add_file sls_sdhc_crc16_1bit.v {SYNTHESIS SIMULATION}
add_file sls_sdhc_crc16_4bit.v {SYNTHESIS SIMULATION}
add_file sls_sdhc_crc7.v {SYNTHESIS SIMULATION}
add_file sls_sdhc_data.v {SYNTHESIS SIMULATION}
add_file sls_sdhc_dma_rd.v {SYNTHESIS SIMULATION}
add_file sls_sdhc_dma_wr.v {SYNTHESIS SIMULATION}
add_file sls_sdhc_rx_fifo.v {SYNTHESIS SIMULATION}
add_file sls_sdhc_tx_fifo.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock ptfSchematicName ""

add_interface_port clock reset_n reset_n Input 1
add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave minimumUninterruptedRunLength 1
set_interface_property avalon_slave bridgesToMaster ""
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave addressSpan 16
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave addressAlignment NATIVE
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave printableDevice false

set_interface_property avalon_slave ASSOCIATED_CLOCK clock

add_interface_port avalon_slave AvS_address address Input 4
add_interface_port avalon_slave AvS_chipselect chipselect Input 1
add_interface_port avalon_slave AvS_write_n write_n Input 1
add_interface_port avalon_slave AvS_read_n read_n Input 1
add_interface_port avalon_slave AvS_writedata writedata Input 32
add_interface_port avalon_slave AvS_readdata readdata Output 32
add_interface_port avalon_slave AvS_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave

set_interface_property interrupt_sender ASSOCIATED_CLOCK clock

add_interface_port interrupt_sender AvS_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point master_write
# | 
add_interface master_write avalon start
set_interface_property master_write linewrapBursts false
set_interface_property master_write adaptsTo ""
set_interface_property master_write doStreamReads false
set_interface_property master_write doStreamWrites false
set_interface_property master_write burstOnBurstBoundariesOnly false

set_interface_property master_write ASSOCIATED_CLOCK clock

add_interface_port master_write AvM_wr_writedata writedata Output 8
add_interface_port master_write AvM_wr_write_n write_n Output 1
add_interface_port master_write AvM_wr_chipselect chipselect Output 1
add_interface_port master_write AvM_wr_waitrequest waitrequest Input 1
add_interface_port master_write AvM_wr_address address Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point master_read
# | 
add_interface master_read avalon start
set_interface_property master_read linewrapBursts false
set_interface_property master_read adaptsTo ""
set_interface_property master_read doStreamReads false
set_interface_property master_read doStreamWrites false
set_interface_property master_read burstOnBurstBoundariesOnly false

set_interface_property master_read ASSOCIATED_CLOCK clock

add_interface_port master_read AvM_rd_readdata readdata Input 8
add_interface_port master_read AvM_rd_read_n read_n Output 1
add_interface_port master_read AvM_rd_address address Output 32
add_interface_port master_read AvM_rd_waitrequest waitrequest Input 1
add_interface_port master_read AvM_rd_readdatavalid readdatavalid Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_start
# | 
add_interface conduit_start conduit start

set_interface_property conduit_start ASSOCIATED_CLOCK clock

add_interface_port conduit_start SD_CLK export Output 1
add_interface_port conduit_start SD_CMD export Bidir 1
add_interface_port conduit_start SD_DAT0 export Bidir 1
add_interface_port conduit_start SD_DAT1 export Bidir 1
add_interface_port conduit_start SD_DAT2 export Bidir 1
add_interface_port conduit_start SD_DAT3 export Bidir 1
add_interface_port conduit_start SD_In export Input 1
add_interface_port conduit_start SD_Wp export Input 1
add_interface_port conduit_start SD_Busy export Output 1
# | 
# +-----------------------------------
